services:
  redis:
    image: redis:7-alpine
    container_name: searxng-redis
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - searxng
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "${SEARXNG_PORT:-7777}:${SEARXNG_PORT:-7777}"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_PROTOCOL=${SEARXNG_PROTOCOL:-http}
      - SEARXNG_HOST=${SEARXNG_HOST:-localhost}
      - SEARXNG_PORT=${SEARXNG_PORT:-7777}
      - GRANIAN_PORT=${SEARXNG_PORT:-7777}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://localhost:7777}
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-supersecretkey}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - searxng
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SEARXNG_HOST:-localhost}:${SEARXNG_PORT:-7777}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  searxng-mcp:
    build: ./mcp-server
    container_name: searxng-mcp
    ports:
      - "${SEARXNG_MCP_PORT:-7778}:${SEARXNG_MCP_PORT:-7778}"
    environment:
      - SEARXNG_PROTOCOL=${SEARXNG_PROTOCOL:-http}
      - SEARXNG_HOST=searxng
      - SEARXNG_PORT=${SEARXNG_PORT:-7777}
      - PORT=${SEARXNG_MCP_PORT:-7778}
    depends_on:
      - searxng
    networks:
      - searxng
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SEARXNG_HOST:-localhost}:${SEARXNG_MCP_PORT:-7778}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis-data:
    name: searxng-redis-data

networks:
  searxng:
    driver: bridge
